# Generated by Django 3.0 on 2021-04-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0005_auto_20210424_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegpro',
            name='impf',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vegpro',
            name='item_name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='UserPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmers_name', models.CharField(max_length=10)),
                ('item_type', models.CharField(choices=[('A', 'Vegetables'), ('B', 'Fruits')], max_length=10)),
                ('item_name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_status', models.IntegerField(default=0)),
                ('e', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FarMeKart.Vegpro')),
            ],
        ),
    ]
