# Generated by Django 3.0 on 2021-04-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0006_auto_20210427_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='item_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vegpro',
            name='item_type',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('Fruits', 'Fruits')], max_length=10),
        ),
    ]
